# meta-mycustom/recipes-httpd/nginx/files/my-app.conf

server {
    # Listen on port 80 and make this the default server for this port.
    listen 80 default_server;
    listen [::]:80 default_server;

    # Set the document root to the directory where our UI files were installed.
    # This path must match the installation path in the.bbappend file.
    root /var/www/localhost/www;

    # Specify the default file to serve if a directory is requested.
    index index.html index.htm;

    # A descriptive server name (optional for default server).
    server_name my-app.local;

    # Define how to handle requests for files.
    location / {
        # Try to serve the requested file directly ($uri),
        # then try it as a directory ($uri/),
        # otherwise return a 404 Not Found error.
        try_files $uri $uri/ =404;
    }

	location /noauth/ {
		proxy_pass  http://127.0.0.1:8080$request_uri;
	}


	location /api/ {
		proxy_pass  http://127.0.0.1:8080$request_uri;
	}


	location /data_io/ {
		try_files $uri /data_io/index.htm;
	}
}
