# Basic example
timeout 60;
retry 60;
reboot 10;
select-timeout 5;
initial-interval 2;

# Request common options
request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, host-name;
