# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

#FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
BBFILE_COLLECTIONS += "meta-mycustom"
BBFILE_PATTERN_meta-mycustom := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mycustom = "999"

LAYERSERIES_COMPAT_meta-mycustom = "kirkstone langdale"

LAYERDEPENDS_meta-mycustom = " \
    core \
    meta-arago-distro \
"

